### ISSUE TITLE
Allow sidebar to be bigger?

### ISSUE THREAD

**Issue by curtisgibby** [duncannah/better-twitter-redesign#2]
On my ginormously widescreen monitor, there's a lot of wasted space that I think could be filled nicely with the sidebar, allowing it to fill up to 25% of the screen width.

## Current
![image](https://user-images.githubusercontent.com/1086964/86299316-2dcf6100-bbbd-11ea-9481-bb743e263dac.png)

## Proposal

![image](https://user-images.githubusercontent.com/1086964/86299511-b3531100-bbbd-11ea-9499-0cc700309a4f.png)

```css
[data-testid="sidebarColumn"] {
    min-width: 300px;
    max-width: 100%;
    flex-grow: 1;
    width: 25%;
}

[data-testid="sidebarColumn"] > div:first-child > div:last-child {
    width: 100%;
}
```
