### ISSUE TITLE
Tweet button role attribute has changed

### ISSUE THREAD

**Issue by Tomalak** [duncannah/better-twitter-redesign#6]
The tweet button went from `role="button"` to `role="link"` recently.

New working CSS:

```css
/* shrink the tweet button */
a[href='/compose/tweet'][role='link'] {
  width: 45px;
  min-width: 0;
  height: 45px;
  min-height: 0;
  padding: 0; }

a[href='/compose/tweet'][role='link'] span {
  font-size: 90%; }
```
